### ISSUE TITLE
Couldn't launch instance trough script

### ISSUE THREAD

**Issue by ArjuAdhmika** [keithvassallomt/parsec-aws-automation#12]
i'm having a problem when i started the script, it says :

An error occurred (InvalidParameterDependency) when calling the RunInstances operation: The parameter KmsKeyId requires the parameter Encrypted to be set.

and i don't know what it means, can somebody help me?

**Comment by keithvassallomt** [comment]
> 

You have selected to encrypt your EBS volume when creating the instance, which you really don't need to do for this use case. So, either re-create the instance without an encrypted volume, or specify the Encrypted parameter to true. See here for the [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIEncryption.html#AMI-encryption-launch).

**Comment by ArjuAdhmika** [comment]
how do i set the Encrypted parameter to True?

**Comment by ArjuAdhmika** [comment]
okay, Thaks for the answer i solved it by set encryption parameter to True
