### ISSUE TITLE
Would the automatic scripts work with a spot Instance instead of an on-demand Instance?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [keithvassallomt/parsec-aws-automation#3]

**Comment by keithvassallomt** [comment]
That’s what they’re designed to work with. The initial instance you create is on-demand, just so everything has time to get created properly. However, in the launch template you then specify a spot instance, and that’s what the script launches.

**Comment by cookie-monster-bit** [comment]
Yeah, I just re-watched the video and realized that. Thank you for creating this fantastic tutorial and automated script!

**Comment by keithvassallomt** [comment]
> Yeah, I just re-watched the video and realized that. Thank you for creating this fantastic tutorial and automated script!

Thanks mate :)

**Comment by chr1sC0d1ng** [comment]
I have two scripts with different template versions mentioned. I have an AWS template for spot instance and one for on demand. Sometimes there is no spot instance available, so then i run the demand one instead.
This whole thing has been such a time saver Keith, thanks!

**Comment by farhansolodev** [comment]
Hey bro, in your youtube tutorial you mentioned that you pay 26$ a month while playing 3-4 times a week. But in the comments you said that we would have to pay $103.42 which is mostly the data transfer costs. Could you explain the discrepancy?

**Comment by keithvassallomt** [comment]
Please keep comments relevant to the title of the issue (this should have been a separate issue). That being said:

> Hey bro, in your youtube tutorial you mentioned that you pay 26$ a month while playing 3-4 times a week. But in the comments you said that we would have to pay $103.42 which is mostly the data transfer costs. Could you explain the discrepancy?

The $26/month is based on what I spend. It really depends on the hours you play.

Assume you game for around 10 hours a week (40 hours a month). Here are the monthly costs:

AWS:
Instance:
g4dn.xlarge * 40 hrs = $0.38 * 40 = $15.20

EBS Volume:
As per AWS Docs, 1GB x 744h = 1GB-month
So, 1GB x 40h = 0.05 GB-month (40/744)
So, 512GB x 40h = 0.05 x 512 = 27.53GB-Month
27.53GB-Month x $0.116 = $3.19

Snapshot (Assuming 60GB usage):
1GB x 704h = 0.95 GB-month (704/744)
So, 60GB x 704h = 0.95 x 60 = 57GB-Month
57GB-Month x $0.053 = $3.02

Data transfer (assuming 50mbps):
900GB x $0.09 = $81
Lambda: 
$1

Total: $103.41.

That being said, the above is the worst case scenario. You're not always transferring at 50Mbps, and incremental snapshots do not add much cost to the total. So take that as an absolute maximum for 40 hours of gaming a month.

**Comment by farhansolodev** [comment]
Okay atleast it is the worst case scenario...

But what even is this data transfer cost? And why is it so high? Could you explain the numbers behind the calculation you made?

Edit: Nevermind, I figured it out. Thanks though!
