### ISSUE TITLE
Unable to re-create Storage from Snapshots

### ISSUE THREAD

**Issue by prtkdas96** [keithvassallomt/parsec-aws-automation#8]
I have followed all the steps perfectly and I am still unable to resume my Gaming PC back from Snapshot when I terminate my instance. Am I missing any step?

**Comment by keithvassallomt** [comment]
Can you tell me the exact problem you are facing?

- Is the snapshot created?
- Does the Lambda function give errors? Check the error logs and paste them here. 
- Do you get any other error message? If so, paste that here too.

You may want to create the initial snapshot manually, and then use the automated process for other snapshots. When a lot of data has changed (such as installing a massive game), the snapshot may not be created quickly enough, and the function can timeout. Also, using gp3 instead of gp2 EBS type and setting IOPS to 16,000 and throughput to 1,000Mbps helps to speed things up.

**Comment by prtkdas96** [comment]
Hi there! Yes, the snapshot has been created and the Lambda Function did not give me any errors. Whenever I terminate the image, it automatically creates the Snapshot and the AMI is created as well. But after termination, when I run the start-server.sh it creates a new instance with a seperate storage and has no link to the Snapshot. Swapping out the storage disk also did not work.

**Comment by keithvassallomt** [comment]
> But after termination, when I run the start-server.sh it creates a new instance with a seperate storage and has no link to the Snapshot. Swapping out the storage disk also did not work.

You mean the instance is in a new state, i.e., anything you have saved/changed the previous time is not in the new instance? 
When you launch the new instance, it's normal to see a new EBS volume being created. Basically, the changes you made the previous time are saved in the AMI (which is actually in the snapshot). The new EBS volume is created when you launch the instance, and should contain the changes you made last time. If that's not the case, then the snapshot isn't being created properly. Can you please confirm?

**Comment by prtkdas96** [comment]
I guess that the EBS Volume is not being created properly then. I did face an error while running the code regarding the "Snapshot_ID" but it quickly got resolved and worked without any errors. One other problem is whenever I used the start_server.sh, I have been unable to get my admin password. It says that it is going to unlock after 4 minutes. But it never really opens and the option to add the .pem file never really comes up.

**Comment by keithvassallomt** [comment]
>I did face an error while running the code regarding the "Snapshot_ID" but it quickly got resolved and worked without any errors. 

Posting the exact error message might help :)

> One other problem is whenever I used the start_server.sh, I have been unable to get my admin password. 

Yeah, that tends to happen. Although, I wonder why you need the admin password at that point? As long as you've setup Parsec or whatever properly, it should auto-start and your system should become visible in the Parsec client.

**Comment by prtkdas96** [comment]
I could have posted the exact error but that was just the first time when I ran the lambda Function. Let me re-create the Function from scratch and post the results here. Also, for some reason I think since the snapshot is not properly getting configured, there is no Parsec in the machine when a new instance is getting created.

**Comment by prtkdas96** [comment]
I got a success message after running the test run in a Lambda Function. The logs are as follows:
START RequestId: 6b317da3-0d2a-4414-aaa4-762c92b9cd7a Version: $LATEST
Created snapshot: snap-0e9598f9604781547
Removing previous snapshot: snap-0e843b33fa7b2f10c
Removing previous snapshot: snap-0ec4790bb9db6fe83
Deleting EBS volume: vol-0d7a5318d6d242bca, Size: 256 GiB
Created image ami-06d5f784d82910032
END RequestId: 6b317da3-0d2a-4414-aaa4-762c92b9cd7a
REPORT RequestId: 6b317da3-0d2a-4414-aaa4-762c92b9cd7a	Duration: 17708.29 ms	Billed Duration: 17709 ms	Memory Size: 128 MB	Max Memory Used: 87 MB

**Comment by keithvassallomt** [comment]
Is that still not working? Because if so, I'm at a bit of a loss here since the function has produced no errors. What is the exact issue you have? Are you not able to login to the server, or do you manage to login but find that the things you downloaded/saved the last time are not there?

**Comment by prtkdas96** [comment]
After I am done with terminating the instance and starting the server from the start_server.ps1, it creates the instances and moves to the running state. But I cannot login to the server or view the instance in parsec. Not sure how to proceed from here.

**Comment by prtkdas96** [comment]
This is what I am getting after running the ps script:
Launching new instance with AMI id: ami-0e49d111e7e600542
{
    "Groups": [],
    "Instances": [
        {
            "AmiLaunchIndex": 0,
            "ImageId": "ami-0e49d111e7e600542",
            "InstanceId": "i-0dad1e689c81be8ab",
            "InstanceType": "g4dn.xlarge",
            "KeyName": "GamingPC",
            "LaunchTime": "2021-06-02T09:39:36+00:00",
            "Monitoring": {
                "State": "disabled"
            },
            "Placement": {
                "AvailabilityZone": "ap-south-1b",
                "GroupName": "",
                "Tenancy": "default"
            },
            "Platform": "windows",
            "PrivateDnsName": "ip-172-31-7-116.ap-south-1.compute.internal",
            "PrivateIpAddress": "172.31.7.116",
            "ProductCodes": [],
            "PublicDnsName": "",
            "State": {
                "Code": 0,
                "Name": "pending"
            },
            "StateTransitionReason": "",
            "SubnetId": "subnet-59dc8115",
            "VpcId": "vpc-a6c600cd",
            "Architecture": "x86_64",
            "BlockDeviceMappings": [],
            "ClientToken": "6dca7e3f-fe82-4786-9d9d-6eb868e766b3",
            "EbsOptimized": false,
            "EnaSupport": true,
            "Hypervisor": "xen",
            "InstanceLifecycle": "spot",
            "NetworkInterfaces": [
                {
                    "Attachment": {
                        "AttachTime": "2021-06-02T09:39:36+00:00",
                        "AttachmentId": "eni-attach-07fe4b5cc70010b2c",
                        "DeleteOnTermination": true,
                        "DeviceIndex": 0,
                        "Status": "attaching",
                        "NetworkCardIndex": 0
                    },
                    "Description": "",
                    "Groups": [
                        {
                            "GroupName": "Moonlight and RDP Ports",
                            "GroupId": "sg-0e804a470e8d1cdfe"
                        }
                    ],
                    "Ipv6Addresses": [],
                    "MacAddress": "0a:e4:a2:fe:82:12",
                    "NetworkInterfaceId": "eni-0d972e8bc6aa9c195",
                    "OwnerId": "380043535463",
                    "PrivateDnsName": "ip-172-31-7-116.ap-south-1.compute.internal",
                    "PrivateIpAddress": "172.31.7.116",
                    "PrivateIpAddresses": [
                        {
                            "Primary": true,
                            "PrivateDnsName": "ip-172-31-7-116.ap-south-1.compute.internal",
                            "PrivateIpAddress": "172.31.7.116"
                        }
                    ],
                    "SourceDestCheck": true,
                    "Status": "in-use",
                    "SubnetId": "subnet-59dc8115",
                    "VpcId": "vpc-a6c600cd",
                    "InterfaceType": "interface"
                }
            ],
            "RootDeviceName": "/dev/sda1",
            "RootDeviceType": "ebs",
            "SecurityGroups": [
                {
                    "GroupName": "Moonlight and RDP Ports",
                    "GroupId": "sg-0e804a470e8d1cdfe"
                }
            ],
            "SourceDestCheck": true,
            "SpotInstanceRequestId": "sir-vymrni9m",
            "StateReason": {
                "Code": "pending",
                "Message": "pending"
            },
            "Tags": [
                {
                    "Key": "aws:ec2launchtemplate:version",
                    "Value": "7"
                },
                {
                    "Key": "SnapAndDelete",
                    "Value": "True"
                },
                {
                    "Key": "Name",
                    "Value": "MoonlightRig"
                },
                {
                    "Key": "aws:ec2launchtemplate:id",
                    "Value": "lt-0092ca2cb53bae561"
                }
            ],
            "VirtualizationType": "hvm",
            "CpuOptions": {
                "CoreCount": 2,
                "ThreadsPerCore": 2
            },
            "CapacityReservationSpecification": {
                "CapacityReservationPreference": "open"
            },
            "MetadataOptions": {
                "State": "pending",
                "HttpTokens": "optional",
                "HttpPutResponseHopLimit": 1,
                "HttpEndpoint": "enabled"
            },
            "EnclaveOptions": {
                "Enabled": false
            }
        }
    ],
    "OwnerId": "380043535463",
    "ReservationId": "r-07ccac9054586e2dc"
}

**Comment by keithvassallomt** [comment]
> After I am done with terminating the instance and starting the server from the start_server.ps1, it creates the instances and moves to the running state. But I cannot login to the server or view the instance in parsec. Not sure how to proceed from here.

Make sure that:

1. You enable automatic login on the instance: [See guide here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/turn-on-automatic-logon)
2. Set Parsec to run on startup: [More info here](https://support.parsec.app/hc/en-us/articles/115002702331-Setting-Up-Hosting-On-Windows) - the Parsec cloud preparation tool tries to do this automatically, but it doesn't always work.

**Comment by dropitlikecross** [comment]
Ran into the same issue here all of a sudden while I had everything working. Maybe some update changed some values somewhere?
I set this up originally in a very messy way when I had no clue about AWS's platform but I'm wiping all and I'll first attempt to recreate with the guide to test and if I can't, then I'll post back here otherwise assume it worked fine.
Also wouldn't this be easier to turn into a cloud formation?

**Comment by keithvassallomt** [comment]
Let me know how the new setup goes :)

> Also wouldn't this be easier to turn into a cloud formation?

It would be easier if someone turned it into a cloud formation, but it wouldn’t be easy at all to turn it into a cloud formation :) Plus there may be license issues with distribution of an AMI with preinstalled Nvidia drivers.
